name: Build GTK themes

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y sassc wget p7zip-full

      - name: Build GTK themes
        run: bash make_gtk_theme.sh

      - name: Upload themes
        uses: actions/upload-artifact@v4
        with:
          name: gtk-themes
          path: gtk-themes.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: gtk-themes.zip
          generate_release_notes: true